name:                autobank
version:             0.0.0.0
github:              "dimasinger/autobank"
license:             MIT
author:              "Dima"
maintainer:          "41106023+dimasinger@users.noreply.github.com"
copyright:           "2019 Dima"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/autobank#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  autobank-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - autobank

tests:
  autobank-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - autobank
